title: "Domain Models Reference"
description: "A wiki-style reference for domain models with fixed sidebar navigation."
theme: jekyll-theme-cayman
markdown: kramdown
baseurl: ""  # adjust if necessary
