title: "Domain Models Reference"
description: "A wiki-style reference for domain models with fixed sidebar navigation."
remote_theme: poole/hyde
plugins:
  - jekyll-remote-theme
markdown: kramdown
baseurl: ""  # adjust if necessary
